apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: prod
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: UEAkc3cwcmQxMjM=  # P@$sw0rd123
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: dev
type: Opaque
data:
  not-a-real-key: NOT-A-REAL-KEY  
  aws-access-key: SecretACCESSKEYVAL  # AKIAXXXXXXXXXXXXXXXXXXXX
  aws-secret-key: Wk1RN2JXbkZLZGsyVEVzdDNkU2VjcmV0S2V5MTIzNDU2Nzg5MA==  
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-signing-key
  namespace: ops
type: Opaque
data:
  private-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzVNWEpFRXZhK2VDOVIKWVhFPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t  # Truncated base64 encoded private key
  public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzVEZ5UkJMMnZuZ3ZVV0Z4Cg==  # Truncated base64 encoded public key
