name: Build and Publish Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Container tag to use'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.event.inputs.tag || 'latest' }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: evil-pod
            path: internal_resources/apps/evil-pod
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.app.path }}
          push: true
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.app.name }}:${{ env.IMAGE_TAG }}
          build-args: |
            GOOS=${{ matrix.platform.os }}
            GOARCH=${{ matrix.platform.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

